AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

# Exceptions
Security/Eval:
  Exclude: ['spec/support/helpers.rb']

# Disabled
Naming/ConstantName:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
