language: ruby
env: DEBUG=true
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 2.3.4
  - 2.4.1
  - 2.5.0
  - ruby-head
  - jruby-head
before_install:
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - gem uninstall -x bundler || true
  - gem install bundler -v '~> 1.7'
matrix:
  include:
    - rvm: 1.8.7
      gemfile: spec/gemfiles/Gemfile.18
    - rvm: jruby-18mode
      gemfile: spec/gemfiles/Gemfile.18
    - rvm: 1.9.3
      gemfile: spec/gemfiles/Gemfile.19
    - rvm: jruby-19mode
      gemfile: spec/gemfiles/Gemfile.19
